"""rename filds

Revision ID: 1a27b0c5da3b
Revises: d4860ae575fe
Create Date: 2025-08-24 15:03:23.213034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a27b0c5da3b'
down_revision: Union[str, Sequence[str], None] = 'd4860ae575fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_resources', sa.Column('hospital_id', sa.String(), nullable=True))
    op.drop_column('hospital_resources', 'hospital_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_resources', sa.Column('hospital_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hospital_resources', 'hospital_id')
    # ### end Alembic commands ###
