"""rename filds

Revision ID: d4860ae575fe
Revises: a76775f6c1f7
Create Date: 2025-08-24 01:45:26.006478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4860ae575fe'
down_revision: Union[str, Sequence[str], None] = 'a76775f6c1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_activity', sa.Column('hospital_id', sa.String(), nullable=True))
    op.drop_column('hospital_activity', 'hospital_name')
    op.add_column('hospital_municipality', sa.Column('hospital_id', sa.String(), nullable=True))
    op.add_column('hospital_municipality', sa.Column('municipality_id', sa.String(), nullable=True))
    op.drop_column('hospital_municipality', 'municipality_name')
    op.drop_column('hospital_municipality', 'hospital_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_municipality', sa.Column('hospital_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hospital_municipality', sa.Column('municipality_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hospital_municipality', 'municipality_id')
    op.drop_column('hospital_municipality', 'hospital_id')
    op.add_column('hospital_activity', sa.Column('hospital_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hospital_activity', 'hospital_id')
    # ### end Alembic commands ###
